import { Titillium_Web } from "next/font/google";
import "./globals.css";

const font = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="cs">
      <body className={`${font.className}`}>{children}</body>
    </html>
  );
}
