name: 🔍 Analyze Commits

on:
  workflow_dispatch:

jobs:
  analyze-commits:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for gitpython to analyze commits

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      # Run the analysis script
      - name: Run analyze_json_commits.py
        run: |
          python analysis/analyse_json_commits.py

      # Upload generated files as artifacts
      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: |
            analysis/name_changes.csv
            analysis/debug_log.txt
          if-no-files-found: error